name: label_printer
description: Flutter App for TSC200 Series Label Printer.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
